let shopItemsData = [
    {
      id: "jfhgbvnscs",
      tip:"celeMaiVanduteProduse",
      display:"noDisplay",
      name: "Copacul",
      price: 45,
      desc: "Lorem ipsum dolor sit amet consectetur",
      img: "/images/produs1.jpg",
    },
    {
      id: "ioytrhndcv",
      tip:"celeMaiVanduteProduse",
      display:"noDisplay",
      name: "Office Shirt",
      price: 100,
      desc: "Lorem ipsum dolor sit amet consectetur",
      img: "/images/produs1.jpg",
    },
    {
      id: "wuefbncxbsn",
      tip:"noutatiProduse",
      display:"display",
      name: "T Shirt",
      price: 25,
      desc: "Lorem ipsum dolor sit amet consectetur",
      img: "/images/produs1.jpg",
    },
    {
      id: "thyfsseradhcbcv",
      tip:"noutatiProduse",
      display:"display",
      name: "Mens Suit",
      price: 300,
      desc: "Lorem ipsum dolor sit amet consectetur",
      img: "/images/produs1.jpg",
    },
    {
      id: "thydsafhcbcv",
      tip:"noutatiProduse",
      display:"display",
      name: "Mens Suit",
      price: 300,
      desc: "Lorem ipsum dolor sit amet consectetur",
      img: "/images/produs1.jpg",
    },
    {
      id: "thyasaewqfhcbcv",
      tip:"noutatiProduse",
      display:"display",
      name: "Mens Suit",
      price: 300,
      desc: "Lorem ipsum dolor sit amet consectetur",
      img: "/images/produs1.jpg",
    },
  ];
  